#!/bin/bash
set -uex
set -o pipefail

lava-network broadcast eth0
lava-send "config_`lava-self`" "config=${1}"

sleep infinity&
echo $! > /root/post-target
sleep infinity&
echo $! > /root/post-run

wait `cat /root/post-run` && false
if test $? -eq 143; then true; else false; fi

if test -e "${HOME}"/gather.sh; then
  if ! test -e "${HOME}"/resultsdir; then
    echo "No resultsdir given" >&2
    exit 1
  fi
  "${HOME}"/gather.sh `cat "${HOME}"/resultsdir`
fi

wait `cat /root/post-target` && false
if test $? -eq 143; then true; else false; fi

exit 0
