global env
if {[info exists env(SCHROOT_PORT)]} {
    set_board_info rsh_prog "/usr/bin/ssh -o Port=[getenv SCHROOT_PORT] -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    set_board_info rcp_prog "/usr/bin/scp -o Port=[getenv SCHROOT_PORT] -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
}
if {[info exists env(SCHROOT_SHARED_DIR)]} {
    set_board_info shared_dir "[getenv SCHROOT_SHARED_DIR]"
}
